trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: Build and Test
  steps:
  - script: |
      set -e
      echo "Starting build process..."
      # Example of installing dependencies
      sudo apt-get update
      sudo apt-get install -y make gcc

      echo "Building project..."
      make all

      echo "Running tests..."
      make test
    displayName: 'Build and Test Project'

- job: Lint
  displayName: Code Linting
  steps:
  - script: |
      set -e
      echo "Linting code..."
      # Example of linting
      sudo apt-get update
      sudo apt-get install -y pylint
      pylint **/*.py
    displayName: 'Lint Code'

- job: Cleanup
  displayName: Cleanup Environment
  steps:
  - script: |
      set -e
      echo "Cleaning up..."
      # Cleanup commands
      make clean
    displayName: 'Cleanup'