 trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SequentialJob
  steps:
  - script: echo "Step 1: Starting the pipeline"
    displayName: 'Step 1'

  - script: |
      echo "Step 2: Running build tasks"
      # Replace this with your actual build command
      # Example for a Node.js project:
      npm install
      npm run build
    displayName: 'Step 2: Build'
    continueOnError: true

  - script: |
      echo "Step 3: Running additional tasks"
      # Add your additional commands here
      sleep 5
    displayName: 'Step 3: Additional tasks'

  - script: echo "Step 4: Finishing up"
    displayName: 'Step 4'