trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: AlwaysPass
  steps:
  - script: echo "This pipeline will always pass."
    displayName: 'Print message'
  - script: exit 0
    displayName: 'Success'