trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Starting pipeline..."
  displayName: 'Start Message'
  continueOnError: true

- script: exit 1
  displayName: 'Failing step but pipeline will continue'
  continueOnError: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Running PowerShell script..."
      exit 1
  displayName: 'Failing PowerShell step but pipeline will continue'
  continueOnError: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Running Bash script..."
      exit 1
  displayName: 'Failing Bash step but pipeline will continue'
  continueOnError: true

- task: CmdLine@2
  inputs:
    script: |
      echo "Running CmdLine script..."
      exit 1
  displayName: 'Failing CmdLine step but pipeline will continue'
  continueOnError: true

- script: echo "Pipeline completed successfully!"
  displayName: 'Completion Message'
  continueOnError: true
