trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "This pipeline will always pass, even with errors!"
    displayName: 'Always passing step'

  - script: |
      set +e
      # Run your build, test, or deployment commands here
      # Even if these commands fail, the pipeline will continue
      exit 0
    displayName: 'Ignore errors and ensure pipeline passes'