trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-liner script'

- script: |
    echo "This is a simple pipeline."
    echo "It will pass no matter what."
  displayName: 'Run a multi-line script'
